project:
  type: website

website:
  sidebar:
    style: docked
    logo: stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat151a/spring-2024
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - section: "Lectures"
        contents:
          - lectures/Lecture1.qmd
          - lectures/Lecture1.ipynb
      - href: data.qmd
        text: Datasets
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



