project:
  type: website
  resources:
    - Lecture1_examples.ipynb
  render:
    - "*.ejs"
    - "*.qmd"
    - "*.ipynb"
    - "!PreWebsiteFiles/"

website:
  sidebar:
    style: docked
    logo: stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat151a/spring-2024
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: course_policies.qmd
        text: Course Policies
      - href: lectures/lectures.qmd
        text: Lectures and labs
      - href: assignments/assignments.qmd
        text: Assignments
      - href: datasets/data.qmd
        text: Datasets
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



