---
title: "Lectures and Labs"
subtitle: "Stat 151A: Linear Models"
theme: [sandstone, assets/styles.scss]
sidebar: true
---


- Lecture Jan 16th:
    - [Class organization](Lecture1.qmd)

- Lab Jan 17th:
    - [Style problem](lab1_student_version.Rmd)

- Lecture Jan 18th:
    - [Different kinds of questions](Lecture2_examples.ipynb) 
    - [Note on linear and affine functions](Lecture2_linearity_note.qmd)


---

- Lecture Jan 23rd:
    - [Multilinear regression as loss minimization](Lecture3.qmd)

- Lab Jan 17th:
    - Linear algebra in R

- Lecture Jan 25th:
    - [Multilinear regression as projection](Lecture4.qmd)

---


- Lecture Jan 29th:
    - Quiz 1
    - [Alternative ways to draw lines through points](Lecture5.ipynb)
- Lab Jan 30th:
    - Homework 1 review
- Lecture Feb 1st:
    - [Transformations of regressors: Some payoffs from the linear algebra perspective](Lecture6.qmd)


---

- Lecture Feb 6th:
    - [Univariate statistics and limit theorems](Lecture7.qmd)
- Lab Feb 7th:
    - Homework consultation
- Lecture Feb 8th:
    - [Vector and matrix-valued statistics and limit theorems](Lecture8.qmd)



---

- Lecture Feb 13th:
    - [The Gaussian assumption](Lecture9.qmd)
- Lab Feb 14th:
    - Homework 2 review
- Lecture Feb 15th:
    - [Simulations and the law of large numbers](Lecture10_code.ipynb)


---

- Lecture Feb 20th:
    - [Consistency of OLS and the residual variance under the Gaussian assumptions](Lecture11.qmd)
- Lab Feb 21st:
    - Homework 3 consultation
- Lecture Feb 22nd:
    - [Linear algebra review](LinearAlgebraReview.qmd) and Quiz 2 retake


---

- Lecture Feb 27th:
    - [Residual distribution under normality](Lecture12.qmd)
- Lab Feb 28th:
    - Homework 3 solutions
- Lecture Feb 29th:
    - [Sampling variability of the coefficients](Lecture13.qmd)
