---
title: "Linear Algebra topics"
format:
  html:
    code-fold: false
    code-tools: true
    include-before-body:
     - file: ../macros.md
---

$\LaTeX$


# Summary of prerequisite requirements

For 151A, we require familiarity with the following basic concepts
from linear algebra.  In rough order of importance,

- **Essential:** Basic vector and matrix operations
    - Addition and subtraction
    - Multiplication by scalars
    - Matrix-matrix and matrix-vectror multiplication
    - Vector dot products, norms, and orthogonality
    - Matrix transposes and inverses, symmetric matrices
- **Essential:** Linear systems
    - Representing a linear system as a matrix equation and vice-versa
    - Solving exactly specified linear systems using matrix inverses
- **Very important:** Vector spaces and bases
    - Rank and null spaces of matrices
    - Solution space of linear systems that are not exactly identified
    - Orthogonal vectors and orthonormal bases
- **Helpful:** Eigendecomposition of symmetric, square matrices
    - Eigenvalues and eigenvectors
    - The relationship between an inverse and the eigendecomposition
    - Eigenvectors as an orthonormal basis
    - The trace and determinant as a function of eigenvalues
    - Positive definiteness

There are some (wonderful, useful, fascinating) linear algebra topics that we *won't* require
in 151A, but which are commonly included in an introductory linear algebra course:

- **Not very important for 151A** (but great to know anyway):
    - Manually solving systems of equations (e.g., row-echelon form, permutations)
    - Advanced properties of determinants (e.g. Cramer's rule) 
    - Singular value decompositions
    - Linear operators on abstract spaces (e.g. spaces of polynomials)
    - Eigendecompositions of non-symmetric matrices
    - Factorizations (e.g. LU, QR)
    - Gram-Schmidt orthogonalization (other than knowing that it can be done)
    - Jordan canonical forms
    - Matrix exponentiation and power series



# Introduction to Applied Linear Algebra by Boyd and Vandenberghe

A good book which is freely available online is [Introduction to
Applied Linear Algebra by Boyd and Vandenberghe (B&V)](https://web.stanford.edu/~boyd/vmls/).
For 151A, the following sections and their exercises are useful:

- Vector operations
    - B&V 1.1-1.4 (addition, scalar multiplication, dot product)
    - B&V 3.1, 3.2 (norms --- we will mostly use the Euclidian (L2) norm)
-  Matrix operations
    - B&V 6.1-6.4 (addition, zero and identity, trace, transpose)
    - B&V 10.1 (multiplication)
    - B&V 11.1-11.2 (inverses)
- Linear systems
    - B&V 8.1, 8.2.2, 8.3 (definition and examples)
    - B&V 11.3 (solution via matrix inversions)
- Vector spaces and bases
    - B&V 5.1-5.3 (linear depenAbsolutely necessarydence, bases, orthonormality)

Some more advanced topics not treaded in B&V are eigenvalues
and nullspaces.


# MIT Open Courseware with Gilbert Strang

There are good recorded lectures in the [MIT open courseware linear algebra series](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/).   The corresponding textbook, 
Strang's Introduction to  Linear Algebra, is also good, but is unfortunately not available online through 
the library website, and there are only a few hard copies available. 

Assuming you can get your hands on a copy of the book, here is what I recommend reviewing.
The sections refer to [readings](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/pages/readings/).
The sections in the  [videos](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/video_galleries/video-lectures/) 
do not appear to line up perfectly with the readings, so where they've deviated, I've made my best
guess as to the corresponding video.

- Essential: Sections 3, 6, 10, 14
- Very important: Sections 7, 15, 16, 10 (video 9), 11 (video 9)
- Very helpful: Sections 17, 21, 27 (video 25), 28 (video 25), 33 (video 30)


# Yu Tsumura's website

[The website by Yu Tsumura](https://yutsumura.com/linear-algebra/)
has a wealth of interesting problems with solutions.  Based on the titles,
the following sections could be useful for 151A:

- Introduction to Matrices
- Elementary Row Operations
- Solutions of Systems of Linear Equations
- Linear Combination and Linear Independence
- Nonsingular Matrices
- Inverse Matrices
- Subspaces in Rn
- Bases and Dimension of Subspaces in Rn
- Bases and Coordinate Vectors
- Linear Transformation from Rn to Rm
- Orthogonal Bases
- Introduction to Eigenvalues and Eigenvectors
- Eigenvectors and Eigenspaces
- Dot Products and Length of Vectors

