---
title: "STAT151A Homework 3: Due February 23rd"
author: Your name here
number-sections: true 
number-depth: 1 
format:
  html:
    code-fold: false
    code-tools: true
    include-before-body:
     - file: ../macros.md
---


$\LaTeX$


Normal intervals
========================

For these problems, assume I give you a computer program
that can compute the function $\Phi(z) = \prob{\RV{z} \le z}$
where $\RV{z}$ is a standard scalar-valued random variable.

Let $\RV{x}$ denote a scalar-valued $N(\mu, \sigma^2)$ random variable.
Using only $\Phi(z)$ and elementary arithmetic, construct
functions that evaluate the following:

#### (a)

$a \mapsto \prob{\RV{x} \le a}$


#### (b)

$b \mapsto \prob{\RV{x} \ge b}$

#### (c)

$a, b \mapsto \prob{b \le \RV{x} \le a}$

#### (d)

$a \mapsto \prob{\abs{\RV{x}} \le a}$


#### (e)

$a \mapsto \prob{\abs{\RV{x}} \ge a}$

#### (f)

$a \mapsto \prob{\abs{\RV{x}} > a}$

#### (g)

$a \mapsto \prob{\abs{\RV{x}} = a}$





Multivariate CLT
========================

Let $\RV{\xv}_n$ denote an IID sequence of random
variables in $\rdom{P}$ (not necessarily normal), each with zero mean and 
finite  covariance matrix $\Sigmam$.  Let $\av \in \rdom{P}$ denote a
fixed vector.

#### (a)

Using the univariate CLT, find the limiting distribution of

$$
\frac{1}{\sqrt{N}} \sumn \av^\trans \RV{\xv_n}.
$$

#### (b)

Using the multivariate CLT and the continuous
mapping theorem, find the limiting distribution of

$$
\av^\trans \left( \frac{1}{\sqrt{N}} \sumn \RV{\xv_n}\right).
$$


#### (c)

Now, suppose that $P = 2$ and

$$\Sigmam = 
\begin{pmatrix}
1 & -1 \\
-1 & 1
\end{pmatrix}.
$$

Find the limiting distributions of each of the following expressions:

$$
\begin{aligned}
\frac{1}{\sqrt{N}} \sumn \RV{\xv_n}_1 \rightarrow& \textrm{?}\\
\frac{1}{\sqrt{N}} \sumn \RV{\xv_n}_2 \rightarrow& \textrm{?} \\
\frac{1}{\sqrt{N}} \sumn (\RV{\xv_n}_1 + \RV{\xv_n}_2) \rightarrow& \textrm{?}
\end{aligned}
$$

(This result demonstrates why it's not enough to only look at
the marginal distribution of the vector components when using
a multivariate CLT.)




Valid covariance matrices
================================

Suppose I were to tell you that the vector-valued random variable 
$\xv$ has a covariance matrix $\cov{\xv} = \Sigmam$ where
$\Sigmam$ is not positive semi-definite (i.e., $\Sigmam$ has
at least one negative eigenvalue).  Show that, if this
were true, you could construct a scalar-valued random
variable with *negative* variance, which is impossible.

(It follows from this argument every covariance matrix must be
postive semi-definite.)
